version: "3.7"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VER}
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /tmp/elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VER}
    container_name: kibana
    environment:
      SERVER_NAME: kibana.home.by
      ELASTICSEARCH_HOSTS: http://es01:9200

    ports:
      - '5601:5601'

    depends_on:
      - 'es01'

  logstash:
    image: docker.elastic.co/logstash/logstash:${LOGSTASH_VER}
    container_name: logstash
    environment:
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://es01:9200

    volumes:
      - /tmp/logstash:/usr/share/logstash/pipeline

    ports:
      - '1514:1514/udp'
      - '1514:1514/tcp'

    depends_on:
      - 'es01'    
